---
title: "Edgar Josymar Torrejon Magallanes's CV"
author: Edgar Josymar Torrejón Magallanes
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1_DpJ56UN2GQk4ju4EKID2SxiGlppw7KKlpRAOBfuCzA/edit#gid=917338460",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```



Contacto {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Habilidades {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Última actualización `r Sys.Date()`.



Main
================================================================================

Edgar Josymar Torrejón Magallanes {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro")
```



Educación {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Experiencia Profesional {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('professional_experience')
```



Experiencia de Investigación {data-icon=laptop}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('research_experience_aside')
```
:::

```{r}
CV %<>% print_section('research_experience')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>


Docencia  {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('teaching_positions')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>



Publicaciones {data-icon=pencil}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```



Presentaciones en reuniones {data-icon=microphone-alt}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_talks')
```


```{r}
CV %<>% print_links()
```

